# Deploy private cluster using ARM template

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: eastus
  resourceGroupName: 'aks-demo-rg'
  sp: 'SpDevOps'
  
steps:

  # - task: AzureCLI@2
  #   displayName: Create Resource Group
  #   inputs:
  #     azureSubscription: $(sp)
  #     scriptType: 'batch'
  #     scriptLocation: 'inlineScript'
  #     inlineScript: 'az group create -m $(resourceGroupName) -l $(location)'

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Deploy AKS    
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: $(sp)
      subscriptionId: $(subscriptionId)
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroupName)'
      location: '$(location)'
      templateLocation: 'Linked artifact'
      csmFile: 'bicep/aks/main.json'
      csmParametersFile: 'bicep/aks/parameters/main.parameters.json'
      deploymentMode: 'Incremental'
