# Deploy private cluster using ARM template

trigger:
 branches:
   include:
     - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: eastus
  resourceGroupName: 'aks-demo-rg'
  sp: 'SpDevOps'

jobs:
  - job: Bicep
    displayName: Compile Bicep files
    steps:      
      - task: Bash@3
        displayName: Install Bicep
        inputs:
          targetType: 'inline'
          script: |                                    
            # Fetch the latest Bicep CLI binary
            curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
            # Mark it as executable
            chmod +x ./bicep
            # Add bicep to your PATH (requires admin)
            sudo mv ./bicep /usr/local/bin/bicep

#steps:
  # - task: replacetokens@3
  #   displayName: Replace Variables
  #   inputs:
  #     targetFiles: 'bicep/aks/parameters/main.parameters.json'
  #     encoding: 'auto'
  #     writeBOM: true
  #     actionOnMissing: 'warn'
  #     keepToken: false
  #     tokenPrefix: '__'
  #     tokenSuffix: '__'
  #     useLegacyPattern: false
  #     enableTelemetry: true
  # - task: AzureResourceManagerTemplateDeployment@3
  #   displayName: Deploy AKS    
  #   inputs:
  #     deploymentScope: 'Resource Group'
  #     azureResourceManagerConnection: $(sp)
  #     subscriptionId: $(subscriptionId)
  #     action: 'Create Or Update Resource Group'
  #     resourceGroupName: '$(resourceGroupName)'
  #     location: '$(location)'
  #     templateLocation: 'Linked artifact'
  #     csmFile: 'bicep/aks/main.json'
  #     csmParametersFile: 'bicep/aks/parameters/main.parameters.json'
  #     deploymentMode: 'Incremental'
