# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: dev
    displayName: DEV
    jobs:
      - job: Echo
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              
              echo 'Hello world'
        - task: CopyFiles@2
          inputs:
            SourceFolder: 'bicep/aks/workload'
            Contents: 'vote.yml'
            TargetFolder: drop
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
      # - deployment: deploy      
      #   displayName: Deploy
      #   dependsOn: Echo
      #   environment: PublicAKS
      #   strategy:
      #     runOnce:
      #       deploy:
      #         steps:
      #           - task: KubernetesManifest@0
      #             inputs:
      #               action: 'deploy'
      #               kubernetesServiceConnection: SpAksPublic
      #               namespace: 'dev'
      #               manifests: 
