trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: eastus
  resourceGroupName: 'appsrv-demo-rg'
  sp: 'SpDevOps'
  
steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Deploy WebApp    
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: $(sp)
      subscriptionId: $(subscriptionId)
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroupName)'
      location: '$(location)'
      templateLocation: 'Linked artifact'
      csmFile: 'bicep/webappDbServiceEndpoint/infra/main.json'
      csmParametersFile: 'bicep/webappDbServiceEndpoint/infra/main.parameters.json'
      deploymentMode: 'Incremental'
