name: Deploy AKS

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'bicep/aks/*.json'
      - '.github/workflows/aks-infra.yml'

env:
  RESOURCE_GROUP_NAME: aks-demo-rg 
  LOCATION: eastus 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Login to Azure
      - name: Azure Login
        uses: Azure/login@v1.1
        with:          
          creds: ${{ secrets.SP_AZURE_CREDENTIALS }}          
          enable-AzPSSession: false
          
      # Install bicep compiler
      - name: Install Bicep compiler
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          
      # Compile bicep files
      - name: Compile bicep files
        run: |
          bicep build bicep/aks/*.bicep          
          
      # Create resource group
      - name: Create Resource Group
        run: |
          az group create -n ${{ env.RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}          
